### ISSUE TITLE
contact method

### ISSUE THREAD

**Issue by fils** [UW-Deepdive-Infrastructure/app-template#10]
I am working on an application I would like to develop using the app-template.  However, I don't see a contact email or method.

**Comment by cambro** [comment]
Hi Doug! Yes, we've been discussing how best to handle this. We'll set up the private repo for you.

**Comment by fils** [comment]
sounds great!   let me know via email
I'll be at ESIP all week, but that is the perfect venue to do some hacking on this...

**Comment by iross** [comment]
Hi Doug--
I've cloned the app template into a private repository for you to use (https://github.com/UW-Deepdive-Infrastructure/fils-app -- feel free to rename it any way you want). There's example data in the repository for you to start playing with, but if you fill out the "config" file and commit/push the changes, we can provide you with a test set of data composed of relevant documents.

If you have any questions at all, feel free to ask them here, on your repo, or via email (iross@cs.wisc.edu).

Happy hacking!

**Comment by cambro** [comment]
Let us know if you need anything Doug! Looking forward to getting the publications into GDD too!

**Comment by jczaplew** [comment]
Now in wiki
