### ISSUE TITLE
App creation tutorial

### ISSUE THREAD

**Issue by jczaplew** [UW-Deepdive-Infrastructure/app-template#17]
A thorough walkthrough of the app creation process would be incredibly valuable. As a wiki page would be ideal.

**Comment by aazaff** [comment]
I think we've completely moved away from any kind of app-template based workflow (THANKFULLY), so I am closing this.

**Comment by metazool** [comment]
What's the recommended way for us to build a GeoDeepDive application now; by forking and customising the stromatolites demo project? https://github.com/UW-Macrostrat/stromatolites_demo

**Comment by aazaff** [comment]
@metazool Nobody in this thread still works at GDD, so I am going to refer you to @cambro or @iross

**Comment by metazool** [comment]
Thank you for the follow up @aazaff - my colleague Joe has forked the stromatolites project and done a PR https://github.com/jemmings-git/stromatolites_demo/pull/2 and we've pinged @iross about it
