### ISSUE TITLE
config + config.yml. difference = ?

### ISSUE THREAD

**Issue by cambro** [UW-Deepdive-Infrastructure/app-template#22]
Should either consolidate or update [documentation](https://github.com/UW-Deepdive-Infrastructure/app-template/wiki/Configuration-file) to explain why there are two and what goes in each.

**Comment by iross** [comment]
Weird git issue. John removed "config" back in the day, but for some reason it didn't get deleted properly in the repo. Re-deleted it and it's ok now.
