### ISSUE TITLE
Example dataset issue

### ISSUE THREAD

**Issue by nchowes** [UW-Deepdive-Infrastructure/app-template#24]
The example dataset in Getting Started appears corrupted for me. After downloading, I am unable to unzip the file (e.g. I get an "End-of-central-directory signature not found").

**Comment by cambro** [comment]
hi! Sorry about that. We neglected to copy a directory when we shifted servers for geodeepdive.org. Assuming that you were looking for this: https://geodeepdive.org/dev_subsets/example_input.zip

This is now fixed. Can you confirm @nchowes

**Comment by nchowes** [comment]
Hi,

Thanks for the quick fix! I grabbed the file and unzipped successfully. 

This project is a good idea and should really fill a void in the Earth Sciences. Look forward to seeing the questions that are asked/answered with the framework and hopefully getting something going myself :)

Best,
Nick

**Comment by cambro** [comment]
Sweet, glad to hear it! Keep us posted on what you're thinking and if we can help.
