### ISSUE TITLE
Python 3.x support?

### ISSUE THREAD

**Issue by lisp-yuppie** [UW-Deepdive-Infrastructure/app-template#27]
I'd like to use a library (tensorflow_hub) that requires Python 3.5. Is there a way that I can do this? Python is a "supported language", but it's not clear what versions are supported.

**Comment by iross** [comment]
Yes, we can support python 3.5. I'd also encourage you to take a look at
dockerizing your application, which solves the portability and versioning
issue. We put together a guide for creating a docker image here:
https://github.com/UW-xDD/xdd-docker-recipe/ .

**Comment by lisp-yuppie** [comment]
Thanks! That's perfect.
