### ISSUE TITLE
enhance input readme

### ISSUE THREAD

**Issue by cambro** [UW-Deepdive-Infrastructure/app-template#8]
would be good to provide clear descriptions of the source of each file product.  For example, fonts.txt has this:

> Information: Fonttype/Formatting recognition via a custom script. Utilizes the output of the Cuneiform OCR process.

Would be useful to supply exact pathway from document to product for each file/file group

**Comment by cambro** [comment]
also include summary statistics for the total dataset from which the testing set was selected.

**Comment by jczaplew** [comment]
Better descriptions now found here - https://github.com/UW-Deepdive-Infrastructure/app-template/wiki/Data-products
